---
body:
    footsize: big
    headsize: big
    residence: portland
    sanity: none
packageGroups:
    group0: dcom-1.0
    group1: base
parents:
    parent0: bill
    parent1: margaret
system:
    type: dkeyr4-1.0
testconfig:
    homedirectory: abc
    password: '123'
    username: abc
