#!/usr/bin/env python

import os, sys
sys.path.append('.')
from bombardier_core.static_data import OK, FAIL
from bombardier_core.Logger import Logger

HISTORY_FILE = "%s/.bomsh_history" % os.environ['HOME']
LOG_PATH = "%s/.bomsh_log" % os.environ['HOME']

def tryImport(module):
    try:
        exec("import %s" % module)
    except ImportError:
        return FAIL
    return OK

def testModules():
    missingModules = []
    for module in ["yaml", "syck"]:
        if tryImport(module) == FAIL:
            missingModules.append(module)
    if missingModules:
        print " %% ERROR: This system does not have the necessary Python libraries."
        print " %%%% You are missing these modules: %s" % ','.join(missingModules)
        print
        sys.exit(1)


testModules()
import syck
import exceptions
import sys, os, readline, signal
import bombardier_server.cli.libUi as libUi
import bombardier_server.cli.Mode as Mode
import bombardier_server.cli.Slash as Slash
import optparse

# READLINE CONFIGS
readline.parse_and_bind('tab: complete')
readline.parse_and_bind('C-z: "end\n"')
#readline.parse_and_bind('?: "\C-v?\t\d"')
readline.parse_and_bind('set bell-style none')
readline.set_completer_delims(' ')

# DEPRICATED:
def run_scripts(scripts):
    status = OK
    filename = scripts[0]
    lines = open(filename, 'r').readlines()
    mode.batch = True
    for line in lines:
        cmdStatus, cmdOutput = slash.processCommand(line.strip())
        if status == OK:
            status = cmdStatus
    return status

def main_loop(mode, slash):
    clean = False
    while True:
        try:
            mode.setPrompt()
            readline.set_completer(slash.complete)
            if clean:
                command = raw_input(mode.getPrompt())
                clean = False
            else:
                command = raw_input(mode.getPrompt()+readline.get_line_buffer())
            slash.processCommand(command)
        except EOFError, eof:
            if len(mode.exitMethods) > 0:
                status, output = mode.exitMethods[-1](slash)
                libUi.userOutput(output, status)
            else:
                print
                mode.clearBomConnections()
                while mode.childProcesses:
                    os.kill(mode.childProcesses.pop(), signal.SIGTERM)
                readline.write_history_file(HISTORY_FILE)
                if mode.commentCommands:
                    makeComment()
                logComment("User %s ENDED an interactive session" % mode.username)
                sys.exit(0)
            mode.cleanMode(mode.state[-1])
            print
        except exceptions.KeyboardInterrupt, key:
            print
            clean = True

if __name__ == "__main__":
    logger = Logger('bombardier_cli', LOG_PATH)

    parser = optparse.OptionParser("usage: %prog -u user-name <bomsh-script>")
    parser.add_option("-u", "--user", dest="user",
                      help="set the username associated with this session")
    (options, scripts) = parser.parse_args()
    username = None
    if options.user:
        username = options.user

    slash = Slash.Slash(Slash.commands)
    mode = Mode.Mode(Mode.USER, '>', username, logger)
    mode.loadConfig()
    mode.login()
    for command in Slash.commands:
        command.set_mode(mode)

    if scripts:
        status = run_scripts(scripts)
        sys.exit(status)
    libUi.motd(slash.fpOut)
    if os.path.isfile(HISTORY_FILE):
        try:
            readline.read_history_file(HISTORY_FILE)
        except:
            print "%% Unable to read history file %s" % HISTORY_FILE
    main_loop(mode, slash)
